# See http://about.travis-ci.org/docs/user/build-configuration/
sudo: false
language: scala
scala:
   - 2.11.8
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - janekdb@gmail.com
jdk:
  - oraclejdk7
  - oraclejdk8
